spring:
  profiles:
    active: staging
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create