# This configuration file configures the application to run in standalone mode when profile dev is set.
spring:
  profiles:
    active: dev
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:~/users-db;MV_STORE=FALSE;MVCC=FALSE
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
eureka:
  client:
    enabled: false
ribbon:
  histrix:
    enabled: false
  eureka:
    enabled: false
  listOfServers: localhost:5000